### ISSUE TITLE
redmine env production and development

### ISSUE THREAD

**Issue by ashrafalzyoud** [geerlingguy/ansible-role-passenger#15]
why give me multiple Phusion Passenger instances
in my redmine

```
redmine@172:~/4.11$ passenger-status 
*** Cleaning stale instance directory /tmp/passenger.UjIOTlH
    Warning: Operation not permitted @ rb_file_chown - /tmp/passenger.UjIOTlH/.
It appears that multiple Phusion Passenger instances are running. Please
select a specific one by running:

  passenger-status <NAME>

The following Phusion Passenger instances are running:

Name                       PID      Description
--------------------------------------------------------------------------
oR2Fxrti                   41650    nginx/1.18.0 Phusion_Passenger/6.0.6
XBKtMEPL                   89988    nginx/1.18.0 Phusion_Passenger/6.0.6
```
database
```
production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  pool: 10
 
development:
  adapter: mysql2
  database: redmine
  host: localhost
  username: redmine
  password: "redmine"
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
  pool: 10
```
how i can let production and development in same app groub
